### ISSUE TITLE
Error in dictionary_converter.py when trying to append_tag

### ISSUE THREAD

**Issue by stuartcw** [Jackson-S/japanese-dictionary#6]
When trying to compile the dictionary I'm getting the following error. 

`File "/Users/stuartcw/Github/japanese-dictionary/./dictionary_converter.py", line 289, in <module>
    main()
  File "/Users/stuartcw/Github/japanese-dictionary/./dictionary_converter.py", line 273, in main
    d_tag = append_tag(entry_root, "definition")
  File "/Users/stuartcw/Github/japanese-dictionary/./dictionary_converter.py", line 237, in append_tag
    tag.attrib = attribs
TypeError: attrib must be dict, not NoneType`

Please let me know if there is anything I can do to fix or resolve it. Many thanks!

**Comment by Jackson-S** [comment]
Hey, I can’t take a look at this right now but just giving you a heads up that this is an older project and I wrote a replacement a little while back (https://github.com/Jackson-S/JapaneseDictionaryRewrite) and there are builds available if you’re not trying to modify it.

If you are trying to modify it then you should know it’s incredibly hacky and awful code that will just break for no reason. I’m happy to take a look if the above isn’t the case though, just let me know.

**Comment by stuartcw** [comment]
Hi there. Thanks so much for replying. I'll take a look at the replacement. Actually, I didn't look at the code yet. If I get some free time, I'll take a look and see if I can figure it out.
